//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PSEntities : DbContext
    {
        public PSEntities()
            : base("name=PSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Appeal> Appeals { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<UserAppeal> UserAppeals { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
