//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAppeal
    {
        public int Id { get; set; }
        public int UId { get; set; }
        public int AId { get; set; }
    
        public virtual Appeal Appeal { get; set; }
        public virtual User User { get; set; }
    }
}
