//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserAppeals = new HashSet<UserAppeal>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Dob { get; set; }
        public string Gender { get; set; }
        public string Password { get; set; }
        public int SId { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual ICollection<UserAppeal> UserAppeals { get; set; }
    }
}
